### ISSUE TITLE
Internal telemetry

### ISSUE THREAD

**Issue by izaaklauer** [hashicorp/waypoint#2058]
Waypoint should be able to collect and emit key metrics, similar to [Vault](https://www.vaultproject.io/docs/internals/telemetry) and [Consul](https://www.consul.io/docs/agent/telemetry). 

### Tasks:
- [ ] Research consul and vault implementation (and ensure compatibility with HCP)
- [ ] Implement core support for metrics
- [ ] Research and emit key metrics, including the following regions:
    - [ ] Process crashes
    - [ ] Resource usage
    - [ ] Core server metrics (GRPC server, boltdb, etc)
    - [ ] Runner metrics (GRPC server, plugin actions, etc)
    - [ ] CEB metrics (time to launch app process, app crashes, app cpu/memory usage, etc)
- [ ] Document feature use

This will likely be split into multiple sub-tasks.

**Comment by izaaklauer** [comment]
Will likely address https://github.com/hashicorp/waypoint/issues/1527

**Comment by izaaklauer** [comment]
Created multiple smaller issues to address this, all tagged with `telemetry`, viewable [here](https://github.com/hashicorp/waypoint/issues?q=is%3Aissue+is%3Aopen+label%3Atelemetry).
