### ISSUE TITLE
0.7 UI Improvements

### ISSUE THREAD

**Issue by gregone** [hashicorp/waypoint#2391]
Placeholder task for the upcoming UI work. 

### Subtasks
- [x] https://github.com/hashicorp/waypoint/issues/2613
- [x] https://github.com/hashicorp/waypoint/pull/2632
- [x] https://github.com/hashicorp/waypoint/issues/2614
- [x] https://github.com/hashicorp/waypoint/pull/2802
- [x] https://github.com/hashicorp/waypoint/issues/2392
- [x] https://github.com/hashicorp/waypoint/issues/2775
- [x] https://github.com/hashicorp/waypoint/pull/2852
- [x] https://github.com/hashicorp/waypoint/pull/2879
- [x] https://github.com/hashicorp/waypoint/issues/2883

### Stretch goals
- [ ] https://github.com/hashicorp/waypoint/issues/2740
- [x] https://github.com/hashicorp/waypoint/issues/2881
- [x] https://github.com/hashicorp/waypoint/issues/2855

### Out of scope
- [ ] https://github.com/hashicorp/waypoint/issues/2445
