### ISSUE TITLE
Improved project/remoteness selection UX

### ISSUE THREAD

**Issue by izaaklauer** [hashicorp/waypoint#2704]
It would be nice to polish the syntax around selecting projects and selecting remoteness. We should:

###### Phase 1?
- [x] Automatically execute operations remotely if possible

###### Phase 2?
- [x] Deprecate the `-remote` flag in favor of a new `-local` flag
- [x] Deprecate the `status` command's project argument, but warn if we detect its use
- [x] #2853
- [x] Detect if the local git repo is dirty before executing a remote op, and error helpfully if we detect its use (https://github.com/hashicorp/waypoint/pull/2799)
- [x] Improve our error messages when no local waypoint.hcl file is found
- [x] Add a message to the top of each operation logging if it's occurring locally or remotely, and if remotely which task is doing the work (https://github.com/hashicorp/waypoint/pull/2795)

###### Phase 3?
- [x] Deprecate the the `project/app` syntax, but error helpfully if we detect it's use
- [x] Tidy up the [app/project selection codepath](https://github.com/hashicorp/waypoint/blob/62e8150a94378af704225350cda762eb10850da1/internal/cli/base.go#L233-L343) as much as possible

###### Phase 4?
- [x] Unit test the above where it makes sense to do so
- [x] Q/A all of the commands that operate against an app or project to make sure they work as expected. Also test multiple apps in one project.

**Comment by izaaklauer** [comment]
Done!
