### ISSUE TITLE
ui: 0.7 final UI clean up tasks

### ISSUE THREAD

**Issue by sabrinako** [hashicorp/waypoint#2883]
## TASKS (can add more if any are spotted besides the ones listed)
- [x] Overview + timeline are not aligned (baseline of `Status` row should match baseline of `Build` timeline element)
    - [ ] Optional: add horizontal rule under section titles
- [x] Overview: commit information misaligned horizontally
- [x] Alignment of rows in Overview table slightly off (https://github.com/hashicorp/waypoint/issues/2539)
- [ ] Change the handling of image/tag (image + tag should act as one line, image should not wrap, the tag should have overflow handled with ellipsis)
- [x] [Missing spacing in build status](https://github.com/hashicorp/waypoint/issues/2883#issuecomment-1011083872)
- [x] [Tight spacing between header and list on apps list page](https://github.com/hashicorp/waypoint/issues/2883#issuecomment-1011088800)
- [x] [Logs and Exec pages have headings but Deployments, Builds, and Releases pages do not](https://github.com/hashicorp/waypoint/issues/2883#issuecomment-1011105711)
- [x] [Release status is missing some spacing and an icon](https://github.com/hashicorp/waypoint/issues/2883#issuecomment-1011132453)
- [ ] STRETCH GOAL: update the breadcrumbs to include current page when on an artifact's detail page

## Merged
- [x] Clean up styling in dark mode (ensure all coloring looks correct)
- [x] Add additional space after the check mark icons of each line in timeline component
- [x] Fix breadcrumbs (seems like most of them except for deployments are off)
- [x] Page headers with icon are missing (build and release details pages)

**Comment by almonk** [comment]
### Page layout

- [ ] Page headers with icon are missing 
- [ ] Alignment of overview and timeline panel are off, relative to each other (baseline of 'status' should match baseline of 'Build...' for e.g.. Adding the horizontal rules under the headers will help

Design:
<img width="1466" alt="CleanShot 2022-01-10 at 13 25 45@2x" src="https://user-images.githubusercontent.com/51724/148774005-a7a64f0f-d5c3-4283-ba4d-29f85702ff23.png">

Current implentation:
<img width="1400" alt="CleanShot 2022-01-10 at 13 25 51@2x" src="https://user-images.githubusercontent.com/51724/148774010-4b951cd7-977d-4044-8f85-db5547eda0be.png">

---

### Sidebar

- [ ] Remove minimum height constraint for rows
- [ ] Secondary text is too close to top row and should be less prominent (e.g. below)

Desired:
<img width="393" alt="CleanShot 2022-01-10 at 13 36 57@2x" src="https://user-images.githubusercontent.com/51724/148775066-b71d0fb3-801a-457c-9857-19818c6f78a5.png">

Current implentation:
<img width="356" alt="CleanShot 2022-01-10 at 13 33 05@2x" src="https://user-images.githubusercontent.com/51724/148775086-79fadeb6-fe45-4e42-bf82-632667e3c1aa.png">

---

### Timeline

- [ ] Missing spacing between status icon and text

<img width="176" alt="CleanShot 2022-01-10 at 13 38 27@2x" src="https://user-images.githubusercontent.com/51724/148775292-ab957aaa-9ed8-4392-adf8-9b75f3b4a53e.png">

---

### Overview
(In addition to existing issues highlighted...)

- [ ] Commit information is misaligned horizontally with items above
- [ ] Lets reduce the column width of all the titles – I used `100px` as the new width and that looked much better
- [ ] New handling for image titles (below)

<img width="513" alt="CleanShot 2022-01-10 at 13 39 44@2x" src="https://user-images.githubusercontent.com/51724/148775495-1ec1a746-5ae0-4a02-86ab-ccd8582470c1.png">

For the image names, lets let flex take on the hard work of adding ellipsis when it's going to overflow and make the whole image name available on mouseover as a tooltip (or in the `title`)

Before and desired below;

![123](https://user-images.githubusercontent.com/51724/148776402-0fb65026-7f6b-434a-bda8-2a2f6738e1f7.png)

**Comment by jgwhite** [comment]
- [ ] Missing spacing in build status

![CleanShot 2022-01-12 at 15 00 11@2x](https://user-images.githubusercontent.com/34030/149155875-1c40cb21-8687-41ee-99fa-915cea3e1d40.png)

**Comment by jgwhite** [comment]
- [ ] Spacing between header and list on apps list page

![CleanShot 2022-01-12 at 15 12 36@2x](https://user-images.githubusercontent.com/34030/149156818-c77329cb-99df-41ea-aa8a-fd6f80c66210.png)

**Comment by jgwhite** [comment]
- [ ] Logs and Exec pages have headings but Deployments, Builds, and Releases pages do not

Perhaps none of these pages needing a heading anymore?

![CleanShot 2022-01-12 at 15 31 14@2x](https://user-images.githubusercontent.com/34030/149159663-2db9343e-22e8-40c9-b0c1-38a6a0003536.png)

![CleanShot 2022-01-12 at 15 31 02@2x](https://user-images.githubusercontent.com/34030/149159674-b663747f-fcd4-4294-a8ce-15cb75dfd0ac.png)

**Comment by jgwhite** [comment]
@almonk given that we don’t have commit messages available yet (nor are we always guaranteed to have them) what do you think about this heading in the deployment detail page?

![CleanShot 2022-01-12 at 15 50 50@2x](https://user-images.githubusercontent.com/34030/149163461-16de0313-15cc-443e-9d98-32f01645dddf.png)

**Comment by jgwhite** [comment]
- [ ] Release status is missing some spacing and an icon

![CleanShot 2022-01-12 at 15 58 18@2x](https://user-images.githubusercontent.com/34030/149165002-f609b568-89f1-49a2-8c60-62018c6b404d.png)

**Comment by jgwhite** [comment]
- [ ] A couple of small aesthetic issues with the “re-run” button

![CleanShot 2022-01-13 at 12 43 33@2x](https://user-images.githubusercontent.com/34030/149324644-64553ed0-a6ac-45e6-a1ac-5339eef00397.png)

![CleanShot 2022-01-13 at 12 46 46@2x](https://user-images.githubusercontent.com/34030/149324837-7b9036de-7da4-44b0-97c2-24ecad9866be.png)

**Comment by jgwhite** [comment]
- [ ] Image tag alignment

![CleanShot 2022-01-13 at 13 27 39@2x](https://user-images.githubusercontent.com/34030/149330216-4b7346ff-71b2-4228-b6b9-05004c84d62c.png)
